### ISSUE TITLE
Migration Plan Wizard - Step 2 - Import another file

### ISSUE THREAD

**Issue by serenamarie125** [priley86/miq_v2v_ui_plugin#34] opened 2018-02-03 05:30 UTC
Note that this should not be started until the following is completed:
#33 Migration Plan Wizard - Step 2 

If a file has already been imported, the Import button remains active.
If the user decides to import another file, post an confirmation message letting them know the list of VMs will be overwritten with the new import.
Once the user confirms, replace the existing list of VMs with the contents of the imported file.
If the user cancels the import, keep the list of existing VMs

**Comment by vconzola** [comment] 2018-02-09 15:46
![9cd-createplan-vms-import](https://user-images.githubusercontent.com/22823035/36035930-6b7caec8-0d86-11e8-9ea2-f61c6be09f5e.png)

**Comment by mturley** [comment] 2018-02-22 01:46
I noticed that something like this was needed, and almost added a similar feature where the import button turned into a "discard" button allowing you to go back to the import screen.  Glad I saw this before I did that-- I'll do this instead.

This might be part of #51 depending on review/timing.

**Comment by mturley** [comment] 2018-02-23 05:44
@serenamarie125 @vconzola, for now I am implementing this as designed, but in figuring out how to get a warning-modal-inside-a-modal like this, I discovered this piece of wisdom: http://alistapart.com/article/neveruseawarning

Maybe instead, the overwrite operation should happen without a warning, and then a message should appear above the list saying "The existing list was overwritten from your new file. [Undo]" .  It is easy to retain old state and undo replacing it with Redux. So I think that would be cleaner.

**Comment by mturley** [comment] 2018-02-23 05:52
Note that instead of having this "replace" behavior, we could instead have a "clear and go back" behavior. Currently you cannot return to the EmptyState view that tells you to drag-and-drop files. you will get the warning if you try to drag-and-drop again or click import again.  Instead we could have the Import button become a "Clear" or "Discard" button after importing. And if they click that, then they can import again. No need for warning or undo there.

I'm happy to implement it as designed, or with an undo, or with a discard. All 3 are pretty easy. What do you guys think?

**Comment by mturley** [comment] 2018-02-23 06:28
Implemented a barebones version of this with the warning dialog as designed, in PR #51. I think that's worth keeping even if we don't end up making it fancier.

**Comment by mturley** [comment] 2018-02-27 01:40
@vconzola, that's fine by me. Honestly the main reason I suggested the undo, is that in this case it happens to be the reverse, and an undo button (here a clear button, really) would be easier than making the correct design for a confirm dialog following pf patterns. Since this is `stretch`, I didn't spend time on that and my implementation is connected to `window.confirm()` as a placeholder. But if we were to go with the undo/clear button instead, that's a one liner, no placeholder to come back to. I'm happy either way, but the confirm placeholder was just merged with #51

**Comment by mturley** [comment] 2018-02-27 01:43
The other thing that made me hesitant to go with the pf confirm dialog is that we then have a modal-inside-a-modal, which is a little odd looking. Is that a common thing we do? Again either way is fine by me. Sorry to waste time on such a little thing :)

**Comment by serenamarie125** [comment] 2018-02-27 02:44
yup we do modals on modals when it's a confirmation dialog @mturley

**Comment by serenamarie125** [comment] 2018-02-27 02:45
@mturley I agree with @vconzola that the warning dialog is 👍

**Comment by mturley** [comment] 2018-02-27 02:45
Got it! Well, then I'll leave the placeholder confirm and alert calls for now, and we'll come back to this time permitting.

**Comment by mturley** [comment] 2018-03-02 20:38
Closing this because the remaining issue is captured in #102 and still unassigned.

**Closed by mturley** 2018-03-02 20:38 UTC
Labels: stretch
