### ISSUE TITLE
Need to show conversion host name along with path to the migration log file

### ISSUE THREAD

**Issue by vconzola** [priley86/miq_v2v_ui_plugin#288] opened 2018-05-03 12:18 UTC
Per Marco and Tomas users will need to know the name of the conversion host where the log file is located for each migration. This will make it much easier to find the logs and also allow them to "stream" the logs as a migration is in progress. @priley86 says this information is already available to the UI, so it's just a matter of adding it above the path in the popover displayed when you click on the info tip for migration status. Let me know if you need a UX mockup.

**Comment by mturley** [comment] 2018-05-05 00:11
@vconzola as mentioned on Slack I am having trouble reproducing the state where this info tip is happening. It seems like it's a simple change and i've implemented some of it but I can't test my code. Working on fixing that with @priley86 and @AparnaKarve's help. In the meantime I think maybe that mockup would be helpful, actually if it's not a hassle.

**Comment by mturley** [comment] 2018-05-14 15:05
@vconzola do you think you could give me a mockup here? I am not able to reproduce the state in the app perfectly, so I can't find exactly the popover and info tip you're talking about.

**Comment by vconzola** [comment] 2018-05-15 15:54
@mturley Here you go. Let me know if you have questions.
![conversion host in popup](https://user-images.githubusercontent.com/22823035/40068474-b8ca694a-5836-11e8-8a17-9dec1d889483.png)

**Comment by priley86** [comment] 2018-05-17 20:35
Added in #322 - closing.

**Closed by priley86** 2018-05-17 20:35 UTC
Labels: sprint8

**Comment by mturley** [comment] 2018-05-17 20:47
Thanks @priley86.
